base_url = "https://luchetti.dev"
title = "luchetti's blog"
description = "a place for my ramblings and discoveries"
default_language = "en"

compile_sass = true
build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "gruvbox-dark"

[translations]
# Additional languages definition
# You can define language specific config values and translations: 
# title, description, generate_feed, feed_filename, taxonomies, build_search_index
# as well as its own search configuration and translations (see above for details on those)

# You can put any kind of data here. The data
# will be accessible in all templates
# Example:
#     [extra]
#     author = "Famous author"
#
# author value will be available using {{ config.extra.author }} in templates
[extra]
