base_url = "https://luchetti.dev"
default_language = "en"
author = "Gustavo Luís Luchetti"

compile_sass = true
build_search_index = true
smart_punctuation = true
minify_html = true

generate_feed = true
feed_filename = "rss.xml"
feed_limit = 10

[translations]
title = "luchetti's blog"
description = "a place for my ramblings and discoveries"

[languages.br]
generate_feed = true
build_search_index = true

[languages.br.translations]
title = "blog do luchetti"
description = "compartilhando ideias e projetos"

[markdown]
highlight_code = true
highlight_theme = "gruvbox-dark"

# available at {{ config.extra.value }}
[extra]
